export const IMAGE_FIELD_TAGS = [
  "all",
  "landscape",
  "mountains",
  "archive",
] as const;

export type ImageFieldTag = (typeof IMAGE_FIELD_TAGS)[number];

export type ImageFieldDepth = "surface" | "inner";

export type ImageFieldItem = {
  id: string;
  src: string;
  alt: string;
  tags: Exclude<ImageFieldTag, "all">[];
  depth: ImageFieldDepth;
  index: number;
};

export const IMAGE_FIELD_BRAND = "Yudeat";

export const IMAGE_FIELD_SURFACE_ITEMS: ImageFieldItem[] = [
  {
    id: "img-6659",
    src: "/field/IMG_6659.jpg",
    alt: "Field photo IMG 6659",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 0,
  },
  {
    id: "img-6662",
    src: "/field/IMG_6662.jpg",
    alt: "Field photo IMG 6662",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 1,
  },
  {
    id: "img-6663",
    src: "/field/IMG_6663.jpg",
    alt: "Field photo IMG 6663",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 2,
  },
  {
    id: "img-6664",
    src: "/field/IMG_6664.jpg",
    alt: "Field photo IMG 6664",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 3,
  },
  {
    id: "img-6665",
    src: "/field/IMG_6665.jpg",
    alt: "Field photo IMG 6665",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 4,
  },
  {
    id: "img-6687",
    src: "/field/IMG_6687.jpg",
    alt: "Field photo IMG 6687",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 5,
  },
  {
    id: "img-6688",
    src: "/field/IMG_6688.jpg",
    alt: "Field photo IMG 6688",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 6,
  },
  {
    id: "img-6689",
    src: "/field/IMG_6689.jpg",
    alt: "Field photo IMG 6689",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 7,
  },
  {
    id: "img-6690",
    src: "/field/IMG_6690.jpg",
    alt: "Field photo IMG 6690",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 8,
  },
  {
    id: "img-6691",
    src: "/field/IMG_6691.jpg",
    alt: "Field photo IMG 6691",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 9,
  },
  {
    id: "img-6692",
    src: "/field/IMG_6692.jpg",
    alt: "Field photo IMG 6692",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 10,
  },
  {
    id: "img-6693",
    src: "/field/IMG_6693.jpg",
    alt: "Field photo IMG 6693",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 11,
  },
  {
    id: "img-6694",
    src: "/field/IMG_6694.jpg",
    alt: "Field photo IMG 6694",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 12,
  },
  {
    id: "img-6695",
    src: "/field/IMG_6695.jpg",
    alt: "Field photo IMG 6695",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 13,
  },
  {
    id: "img-6703",
    src: "/field/IMG_6703.jpg",
    alt: "Field photo IMG 6703",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 14,
  },
  {
    id: "img-6704",
    src: "/field/IMG_6704.jpg",
    alt: "Field photo IMG 6704",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 15,
  },
  {
    id: "img-6705",
    src: "/field/IMG_6705.jpg",
    alt: "Field photo IMG 6705",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 16,
  },
  {
    id: "img-6706",
    src: "/field/IMG_6706.jpg",
    alt: "Field photo IMG 6706",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 17,
  },
  {
    id: "img-6707",
    src: "/field/IMG_6707.jpg",
    alt: "Field photo IMG 6707",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 18,
  },
  {
    id: "img-6711",
    src: "/field/IMG_6711.jpg",
    alt: "Field photo IMG 6711",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 19,
  },
  {
    id: "img-6712",
    src: "/field/IMG_6712.jpg",
    alt: "Field photo IMG 6712",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 20,
  },
  {
    id: "img-6713",
    src: "/field/IMG_6713.jpg",
    alt: "Field photo IMG 6713",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 21,
  },
  {
    id: "img-6714",
    src: "/field/IMG_6714.jpg",
    alt: "Field photo IMG 6714",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 22,
  },
  {
    id: "img-6715",
    src: "/field/IMG_6715.jpg",
    alt: "Field photo IMG 6715",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 23,
  },
  {
    id: "img-6718",
    src: "/field/IMG_6718.jpg",
    alt: "Field photo IMG 6718",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 24,
  },
  {
    id: "img-6719",
    src: "/field/IMG_6719.jpg",
    alt: "Field photo IMG 6719",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 25,
  },
  {
    id: "img-6720",
    src: "/field/IMG_6720.jpg",
    alt: "Field photo IMG 6720",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 26,
  },
  {
    id: "img-6721",
    src: "/field/IMG_6721.jpg",
    alt: "Field photo IMG 6721",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 27,
  },
  {
    id: "img-6722",
    src: "/field/IMG_6722.jpg",
    alt: "Field photo IMG 6722",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 28,
  },
  {
    id: "img-6723",
    src: "/field/IMG_6723.jpg",
    alt: "Field photo IMG 6723",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 29,
  },
  {
    id: "img-6724",
    src: "/field/IMG_6724.jpg",
    alt: "Field photo IMG 6724",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 30,
  },
  {
    id: "img-6729",
    src: "/field/IMG_6729.jpg",
    alt: "Field photo IMG 6729",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 31,
  },
  {
    id: "img-6730",
    src: "/field/IMG_6730.jpg",
    alt: "Field photo IMG 6730",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 32,
  },
  {
    id: "img-6734",
    src: "/field/IMG_6734.jpg",
    alt: "Field photo IMG 6734",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 33,
  },
  {
    id: "img-6735",
    src: "/field/IMG_6735.jpg",
    alt: "Field photo IMG 6735",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 34,
  },
  {
    id: "img-6736",
    src: "/field/IMG_6736.jpg",
    alt: "Field photo IMG 6736",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 35,
  },
  {
    id: "img-6740",
    src: "/field/IMG_6740.jpg",
    alt: "Field photo IMG 6740",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 36,
  },
  {
    id: "img-6741",
    src: "/field/IMG_6741.jpg",
    alt: "Field photo IMG 6741",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 37,
  },
  {
    id: "img-6742",
    src: "/field/IMG_6742.jpg",
    alt: "Field photo IMG 6742",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 38,
  },
  {
    id: "img-6749",
    src: "/field/IMG_6749.jpg",
    alt: "Field photo IMG 6749",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 39,
  },
  {
    id: "img-6750",
    src: "/field/IMG_6750.jpg",
    alt: "Field photo IMG 6750",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 40,
  },
  {
    id: "img-6756",
    src: "/field/IMG_6756.jpg",
    alt: "Field photo IMG 6756",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 41,
  },
  {
    id: "img-6757",
    src: "/field/IMG_6757.jpg",
    alt: "Field photo IMG 6757",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 42,
  },
  {
    id: "img-6758",
    src: "/field/IMG_6758.jpg",
    alt: "Field photo IMG 6758",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 43,
  },
  {
    id: "img-6759",
    src: "/field/IMG_6759.jpg",
    alt: "Field photo IMG 6759",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 44,
  },
  {
    id: "img-6760",
    src: "/field/IMG_6760.jpg",
    alt: "Field photo IMG 6760",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 45,
  },
  {
    id: "img-6766",
    src: "/field/IMG_6766.jpg",
    alt: "Field photo IMG 6766",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 46,
  },
  {
    id: "img-6768",
    src: "/field/IMG_6768.jpg",
    alt: "Field photo IMG 6768",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 47,
  },
  {
    id: "img-6769",
    src: "/field/IMG_6769.jpg",
    alt: "Field photo IMG 6769",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 48,
  },
  {
    id: "img-6791",
    src: "/field/IMG_6791.jpg",
    alt: "Field photo IMG 6791",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 49,
  },
  {
    id: "img-6792",
    src: "/field/IMG_6792.jpg",
    alt: "Field photo IMG 6792",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 50,
  },
  {
    id: "img-6793",
    src: "/field/IMG_6793.jpg",
    alt: "Field photo IMG 6793",
    tags: ["landscape", "mountains", "archive"],
    depth: "surface",
    index: 51,
  }
];

export const IMAGE_FIELD_INNER_ITEMS: ImageFieldItem[] = [
  {
    id: "img-6794",
    src: "/field/IMG_6794.jpg",
    alt: "Field photo IMG 6794",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 52,
  },
  {
    id: "img-6795",
    src: "/field/IMG_6795.jpg",
    alt: "Field photo IMG 6795",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 53,
  },
  {
    id: "img-6808",
    src: "/field/IMG_6808.jpg",
    alt: "Field photo IMG 6808",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 54,
  },
  {
    id: "img-6809",
    src: "/field/IMG_6809.jpg",
    alt: "Field photo IMG 6809",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 55,
  },
  {
    id: "img-6810",
    src: "/field/IMG_6810.jpg",
    alt: "Field photo IMG 6810",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 56,
  },
  {
    id: "img-6811",
    src: "/field/IMG_6811.jpg",
    alt: "Field photo IMG 6811",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 57,
  },
  {
    id: "img-6812",
    src: "/field/IMG_6812.jpg",
    alt: "Field photo IMG 6812",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 58,
  },
  {
    id: "img-6813",
    src: "/field/IMG_6813.jpg",
    alt: "Field photo IMG 6813",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 59,
  },
  {
    id: "img-6814",
    src: "/field/IMG_6814.jpg",
    alt: "Field photo IMG 6814",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 60,
  },
  {
    id: "img-6815",
    src: "/field/IMG_6815.jpg",
    alt: "Field photo IMG 6815",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 61,
  },
  {
    id: "img-6816",
    src: "/field/IMG_6816.jpg",
    alt: "Field photo IMG 6816",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 62,
  },
  {
    id: "img-6827",
    src: "/field/IMG_6827.jpg",
    alt: "Field photo IMG 6827",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 63,
  },
  {
    id: "img-6828",
    src: "/field/IMG_6828.jpg",
    alt: "Field photo IMG 6828",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 64,
  },
  {
    id: "img-6829",
    src: "/field/IMG_6829.jpg",
    alt: "Field photo IMG 6829",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 65,
  },
  {
    id: "img-6841",
    src: "/field/IMG_6841.jpg",
    alt: "Field photo IMG 6841",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 66,
  },
  {
    id: "img-6842",
    src: "/field/IMG_6842.jpg",
    alt: "Field photo IMG 6842",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 67,
  },
  {
    id: "img-6843",
    src: "/field/IMG_6843.jpg",
    alt: "Field photo IMG 6843",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 68,
  },
  {
    id: "img-6849",
    src: "/field/IMG_6849.jpg",
    alt: "Field photo IMG 6849",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 69,
  },
  {
    id: "img-6850",
    src: "/field/IMG_6850.jpg",
    alt: "Field photo IMG 6850",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 70,
  },
  {
    id: "img-6851",
    src: "/field/IMG_6851.jpg",
    alt: "Field photo IMG 6851",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 71,
  },
  {
    id: "img-6854",
    src: "/field/IMG_6854.jpg",
    alt: "Field photo IMG 6854",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 72,
  },
  {
    id: "img-6855",
    src: "/field/IMG_6855.jpg",
    alt: "Field photo IMG 6855",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 73,
  },
  {
    id: "img-6856",
    src: "/field/IMG_6856.jpg",
    alt: "Field photo IMG 6856",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 74,
  },
  {
    id: "img-6857",
    src: "/field/IMG_6857.jpg",
    alt: "Field photo IMG 6857",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 75,
  },
  {
    id: "img-6858",
    src: "/field/IMG_6858.jpg",
    alt: "Field photo IMG 6858",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 76,
  },
  {
    id: "img-6860",
    src: "/field/IMG_6860.jpg",
    alt: "Field photo IMG 6860",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 77,
  },
  {
    id: "img-6861",
    src: "/field/IMG_6861.jpg",
    alt: "Field photo IMG 6861",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 78,
  },
  {
    id: "img-6862",
    src: "/field/IMG_6862.jpg",
    alt: "Field photo IMG 6862",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 79,
  },
  {
    id: "img-6863",
    src: "/field/IMG_6863.jpg",
    alt: "Field photo IMG 6863",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 80,
  },
  {
    id: "img-6869",
    src: "/field/IMG_6869.jpg",
    alt: "Field photo IMG 6869",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 81,
  },
  {
    id: "img-6870",
    src: "/field/IMG_6870.jpg",
    alt: "Field photo IMG 6870",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 82,
  },
  {
    id: "img-6871",
    src: "/field/IMG_6871.jpg",
    alt: "Field photo IMG 6871",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 83,
  },
  {
    id: "img-6879",
    src: "/field/IMG_6879.jpg",
    alt: "Field photo IMG 6879",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 84,
  },
  {
    id: "img-6881",
    src: "/field/IMG_6881.jpg",
    alt: "Field photo IMG 6881",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 85,
  },
  {
    id: "img-6882",
    src: "/field/IMG_6882.jpg",
    alt: "Field photo IMG 6882",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 86,
  },
  {
    id: "img-6883",
    src: "/field/IMG_6883.jpg",
    alt: "Field photo IMG 6883",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 87,
  },
  {
    id: "img-6884",
    src: "/field/IMG_6884.jpg",
    alt: "Field photo IMG 6884",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 88,
  },
  {
    id: "img-6885",
    src: "/field/IMG_6885.jpg",
    alt: "Field photo IMG 6885",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 89,
  },
  {
    id: "img-6886",
    src: "/field/IMG_6886.jpg",
    alt: "Field photo IMG 6886",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 90,
  },
  {
    id: "img-6887",
    src: "/field/IMG_6887.jpg",
    alt: "Field photo IMG 6887",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 91,
  },
  {
    id: "img-6888",
    src: "/field/IMG_6888.jpg",
    alt: "Field photo IMG 6888",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 92,
  },
  {
    id: "img-6889",
    src: "/field/IMG_6889.jpg",
    alt: "Field photo IMG 6889",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 93,
  },
  {
    id: "img-6898",
    src: "/field/IMG_6898.jpg",
    alt: "Field photo IMG 6898",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 94,
  },
  {
    id: "img-6899",
    src: "/field/IMG_6899.jpg",
    alt: "Field photo IMG 6899",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 95,
  },
  {
    id: "img-6900",
    src: "/field/IMG_6900.jpg",
    alt: "Field photo IMG 6900",
    tags: ["landscape", "mountains", "archive"],
    depth: "inner",
    index: 96,
  }
];

export const IMAGE_FIELD_ALL_ITEMS: ImageFieldItem[] = [
  ...IMAGE_FIELD_SURFACE_ITEMS,
  ...IMAGE_FIELD_INNER_ITEMS,
];
